[package]
name = "nisemono"
version = "0.1.0"
authors = ["jeremy <jeyx.22@gmail.com>"]
edition = "2018"

[dependencies]
smoltcp = "0.6.0"
systemstat = "0.1.5"
tui = "0.10.0"
termion = "1.5.5"
regex = "1.3.9"
